name: "Sense 360 Zone Configurator"
description: "Helps you to visually create zones for mmWave Presence Sensors with Sense 360 technology for Home Assistant"
version: "1.2.1"
slug: "sense-360-zone-configurator"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
ingress: true
ingress_port: 8099
ingress_entry: index.html
panel_icon: "mdi:radar"
ports:
  8099/tcp: null
homeassistant_api: true
